# Site settings
title: Ruby / JavaScript Development Thoughts
email: toby.osbourn@gmail.com
description: Thoughts and musings on web development and other topics
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
permalink: /:title

# Build settings
markdown: kramdown
